package it.polimi.ingsw.server.model;

import it.polimi.ingsw.network.events.UpdateBoardEvent;
import it.polimi.ingsw.network.objects.ObjState;
import it.polimi.ingsw.server.model.gameComponents.Board;
import it.polimi.ingsw.server.model.gameComponents.Box;
import it.polimi.ingsw.server.model.gameComponents.Player;
import it.polimi.ingsw.server.model.gameState.GameState;
import it.polimi.ingsw.server.model.god.God;
import it.polimi.ingsw.server.model.playerState.PlayerState;

import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;

public interface GameModel {
    Board getBoard();
    int getColumnWorker(int indexWorker);
    int getRowWorker(int indexWorker);
    ArrayList<Player> getPlayerArray();
    int getNPlayers();
    void setNPlayers(int nPlayers);
    void startGame();
    void addPlayer(int indexClient, Timer timer, TimerTask timerTask);
    boolean addPlayer(String name, int age, int indexClient);
    boolean checkAckPlayer();
    void removeExtraPlayer();
    void remove(int indexPlayer);
    boolean askState();
    int searchByName(String name);
    int searchByClientIndex(int indexClient);
    int searchByPlayerIndex(int playerIndex);
    ArrayList<String> getCards()throws Exception;
    UpdateBoardEvent gameData(boolean reach);
    ArrayList<String> getTempCard();
    ArrayList<String> getCardUsed();
    int chooseTempCard(ArrayList<Integer> tempCard);
    int chooseCard(int godCard);
    int whoIsPlaying();
    void goPlayingNext();
    boolean initializeWorker(Box box1, Box box2);
    GameState getState();
    ArrayList<Box> getWorkersPos(int indexPlayer);
    boolean isReachable(int row, int column);
    boolean canMove();
    boolean canMoveSpecialTurn(int indexWorker);
    boolean canBuildBeforeWorkerMove();
    void setBoxReachable(int indexWorker);
    boolean movePlayer(int indexWorker, int row, int column);
    boolean canBuild(int indexWorker);
    void setBoxBuilding(int indexWorker);
    boolean buildBlock(int indexWorker, int row, int column);
    void setIndexPossibleBlock(int indexPossibleBlock);
    boolean checkWin(int rowStart, int columnStart, int indexWorker);
    boolean checkWinAfterBuild();
    int getWinner();
    void setDeadPlayer(int indexPlayer);
    void setPause();
    void controlHeartBeat(int indexClient);
    boolean incrementHeartBeat(int indexClient);
    void reset();
}
